---
- name: Ensure Logstash SSL key pair directory exists.
  file:
    path: "{{ logstash_ssl_dir }}"
    state: directory
  when: logstash_ssl_key_file is defined and logstash_ssl_dir != ""

- name: Copy SSL key and cert and CA cert for beats input.
  copy:
    src: "{{ item }}"
    dest: "{{ logstash_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ logstash_ssl_key_file }}"
    - "{{ logstash_ssl_certificate_file }}"
    - "{{ logstash_ssl_certificate_authority }}"
  notify: restart logstash
  when:
    - logstash_ssl_dir is defined and logstash_ssl_dir != ""
    - logstash_ssl_key_file is defined and logstash_ssl_key_file != ""
    - logstash_ssl_certificate_file is defined and logstash_ssl_certificate_file != ""
    - logstash_ssl_certificate_authority is defined and logstash_ssl_certificate_authority != ""
